### ISSUE TITLE
LiveXAML not working in Android project using Xamarin Forms Embedding

### ISSUE THREAD

**Issue by pravin271** [OYIon/XamarinFormsLive#58] opened 2018-07-24 04:42 UTC
Hi, I have purchased the one month license and added liveXAML NuGet package in an android project. (Solution contains multiple Android projects).

Upon saving changes XAML file, nothing is updated on the emulator. I have checked the logs, looks like nothing is printing related to liveXAML. 

What can be the problem? I am on windows with Visual Studio 2017 15.7

**Comment by ionoy** [comment] 2018-07-24 05:10
Most likely, the issue is that you don't have an `App.xaml` file in your project. Is this true?

**Comment by pravin271** [comment] 2018-07-24 05:11
Yes, we don't have app.xaml in the project. Any workaround?

**Comment by ionoy** [comment] 2018-07-24 05:15
Is it possible to add `App.xaml` in your project? 

Otherwise, you can use this code in the initializer. This will compile fine, but it will show a red squiggle in Visual Studio. 

```
 #if !DISABLE_XAMARINFORMSLIVE
   __livexaml.Runtime.Initialize();
#endif
```

**Comment by pravin271** [comment] 2018-07-24 05:18
getting the following error for the second option and the red squiggle,

'Runtime' does not contain a definition for 'Initialize'

**Comment by ionoy** [comment] 2018-07-24 05:22
What if you do something like this?

```
#if !DISABLE_XAMARINFORMSLIVE
   var instance = __livexaml.Listener.Instance;
#endif
```

(sorry for guessing, I'm not at the work PC right now)

**Comment by pravin271** [comment] 2018-07-24 05:26
this one builds.

**Comment by pravin271** [comment] 2018-07-24 05:32
but the code doesn't compile after adding __livexaml.Runtime.Initialize();

**Comment by ionoy** [comment] 2018-07-24 05:34
You shouldn't need `Initialize()` call with this one. Can you try debugging and see if "XL: ..." messages show up?

**Comment by pravin271** [comment] 2018-07-24 05:35
Okay. will let you know.

**Comment by pravin271** [comment] 2018-07-24 05:50
Checked. Still, no messages in the output window.

**Comment by pravin271** [comment] 2018-07-24 05:56
I have changed my code to call following in every activity,
#if !DISABLE_XAMARINFORMSLIVE
   var instance = __livexaml.Listener.Instance;
#endif

Seeing following messages in output window but after making changes in XAML raises following error in emulator,

[0:] XL: Listener received a message (91900)
[0:] XL: Updated element not found: IraTrips.Business.Views.PlaceDetailsView
[0:] XL: Reloading the current page
[0:] XL: InitializeComponent 
[0:] XL: Object reference not set to an instance of an object.
[0:] XL: Listener received a message (7200)
[0:] XL: Listener received a message (84700)

![image](https://user-images.githubusercontent.com/20390352/43119482-311caa3c-8f34-11e8-8d38-77143deadeb1.png)

**Comment by pravin271** [comment] 2018-07-25 03:27
Hi, this is working for most of the other pages and not for the page mentioned above. 

Also, what we need to do for iOS App without app.xaml file? Do we need to add the same code in each controller that we have?

**Comment by pravin271** [comment] 2018-07-28 17:03
Any help would be great. Still struggling with this. Not able to use above solution in iOS and it is not working with all pages in android.

**Comment by ionoy** [comment] 2018-07-29 05:45
Sorry for the late reply!

You only need to call `var instance = __livexaml.Listener.Instance;` once during app initialization. 

As for Null Reference Exception, you can check Common Language Runtime Exceptions in "Exception Settings" window.

![image](https://user-images.githubusercontent.com/592624/43363354-a89cf000-930b-11e8-9c99-94e349dc74c2.png)

This will break the debugger once the exception happens. Please do that.

**Comment by ionoy** [comment] 2018-10-02 08:14
I'm closing this issue. Please reopen if the problem persists.

**Closed as completed by ionoy** 2018-10-02 08:14 UTC
